<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SBE2UEF" failures="1" tests="3" name="cucumberrunner.Runnerfile" time="32.072" errors="0" timestamp="2024-05-30T12:14:51 IST" skipped="0">
  <testcase classname="cucumberrunner.Runnerfile" name="runScenario" time="6.715"/>
  <system-out/>
  <testcase classname="cucumberrunner.Runnerfile" name="runScenario" time="17.057"/>
  <system-out/>
  <testcase classname="cucumberrunner.Runnerfile" name="runScenario" time="8.300">
    <failure message="failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/cart.html]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/cart.html]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at functionalstep.cartsteps.click_on_cart_btn(cartsteps.java:39)
at stepddefination.cartbtn.click_on_cart_btn(cartbtn.java:24)
at âœ½.click on cart btn(file:///F:/automationtesting/AutomationProject/src/test/java/features/Cartbtn.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- cucumberrunner.Runnerfile -->
